---
# install auditd
- name: ensure auditd running
  service:
    name: auditd
    state: started

# copy audit.rules based on criteria
- name: copy cent6 version
  copy:
    src: cent6.default.audit.rules
    dest: /etc/audit/rules.d/audit.rules
  notify:
  - restart auditd
  when: 
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

- name: copy cent7 version
  copy:
    src: cent7.default.audit.rules
    dest: /etc/audit/rules.d/audit.rules
  notify:
  - restart auditd
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: copy cent8 version
  copy:
    src: cent8.default.audit.rules
    dest: /etc/audit/rules.d/audit.rules
  notify:
  - restart auditd
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"
